In [1]:
print ("15 lakhs per anum ")

15 lakhs per anum

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\R.K COM\Downloads\sales_raw_500.xlsx - Sheet1.csv')

In [4]:
df.head()

   Order_ID Order_Date Customer Region  Product  Sales   Cost
0      1001  1/13/2023    Rohit  South   Mobile  23289  19118
1      1002  10/7/2023     Aman   West   Laptop   8905   5593
2      1003  11/5/2023    Rahul  South  Monitor  59987  39959
3      1004  2/19/2024    Rahul  South  Printer  49597  33892
4      1005  1/26/2024   Anjali  North   Laptop  54797  34468

In [5]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer', 'Region', 'Product', 'Sales',
       'Cost'],
      dtype='str')

In [8]:
df.isnull().sum()

Order_ID       0
Order_Date    18
Customer       0
Region         0
Product        0
Sales          0
Cost           0
dtype: int64

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    520 non-null    int64
 1   Order_Date  502 non-null    str
 2   Customer    520 non-null    str
 3   Region      520 non-null    str
 4   Product     520 non-null    str
 5   Sales       520 non-null    int64
 6   Cost        520 non-null    int64
dtypes: int64(3), str(4)
memory usage: 28.6 KB

In [15]:
df = df.drop_duplicates()

In [16]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001  1/13/2023    Rohit  South   Mobile  23289  19118
1        1002  10/7/2023     Aman   West   Laptop   8905   5593
2        1003  11/5/2023    Rahul  South  Monitor  59987  39959
3        1004  2/19/2024    Rahul  South  Printer  49597  33892
4        1005  1/26/2024   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
495      1496  4/24/2023    Kiran  North  Printer  23434  16388
496      1497  6/27/2023   Anjali  South   Laptop  49007  35970
497      1498   5/8/2023     Aman   East   Tablet  19160  15636
498      1499        NaN    Pooja   West   Mobile  59266  44326
499      1500  10/7/2023    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [27]:
# DROP DATE COLUMN WHERE BLANKS COLUMNS 

df['Order_Date'] = pd.to_datetime(df['Order_Date'],errors='coerce')

df = df.dropna(subset=['Order_Date'])

In [28]:
#create new columns

df['Year'] = df['Order_Date'].dt.year

In [29]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost  Year
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118  2023
1        1002 2023-10-07     Aman   West   Laptop   8905   5593  2023
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959  2023
3        1004 2024-02-19    Rahul  South  Printer  49597  33892  2024
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468  2024
..        ...        ...      ...    ...      ...    ...    ...   ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931  2023
495      1496 2023-04-24    Kiran  North  Printer  23434  16388  2023
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970  2023
497      1498 2023-05-08     Aman   East   Tablet  19160  15636  2023
499      1500 2023-10-07    Vikas  North  Printer  34567  22426  2023

[482 rows x 8 columns]

In [32]:
df['Months'] = df['Order_Date'].dt.month

df

     Order_ID Order_Date Customer Region  Product  Sales   Cost  Year  Months
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118  2023       1
1        1002 2023-10-07     Aman   West   Laptop   8905   5593  2023      10
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959  2023      11
3        1004 2024-02-19    Rahul  South  Printer  49597  33892  2024       2
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468  2024       1
..        ...        ...      ...    ...      ...    ...    ...   ...     ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931  2023      10
495      1496 2023-04-24    Kiran  North  Printer  23434  16388  2023       4
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970  2023       6
497      1498 2023-05-08     Aman   East   Tablet  19160  15636  2023       5
499      1500 2023-10-07    Vikas  North  Printer  34567  22426  2023      10

[482 rows x 9 columns]

In [33]:
df['Profit'] = df ['Sales'] - df['Cost']

In [34]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Year,Months,Profit
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,2023,1,4171
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,2023,10,3312
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,2023,11,20028
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,2024,2,15705
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,2024,1,20329
...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,2023,10,5778
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,2023,4,7046
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,2023,6,13037
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,2023,5,3524
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,2023,10,12141

In [38]:
# For save data

df.to_csv('Sales_cleaned.csv', index= False)   # index = False for index column

In [41]:
# python to sql data

import pandas as pd
 
!pip install sqlalchemy
from sqlalchemy import create_engine

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.50-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.1-cp314-cp314-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\R.K COM\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.50-cp314-cp314-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 1.1 MB/s eta 0:00:02
   -------------- ------------------------- 0.8/2.1 MB 1.4 MB/s eta 0:00:01
   ------------------- -------------------- 1.0/2.1 MB 1.3 MB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.1 MB 1.5 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 1.6 MB/s  0:00:01
Downloading greenlet-3.5.1-cp314-cp314-win_amd64.whl (239 kB)
Installing collected packages: greenlet, sqlalchemy

   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   ---------------------------------------- 2/2 [sqlalchemy]

Successfully installed greenlet-3.5.1 sqlalchemy-2.0.50

In [44]:
import pandas as pd

df = pd.read_csv('Sales_cleaned_dataset.csv')

In [43]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Year,Months,Profit
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,2023,1,4171
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,2023,10,3312
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,2023,11,20028
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,2024,2,15705
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,2024,1,20329
...,...,...,...,...,...,...,...,...,...,...
477,1495,2023-10-18,Rahul,South,Monitor,46709,40931,2023,10,5778
478,1496,2023-04-24,Kiran,North,Printer,23434,16388,2023,4,7046
479,1497,2023-06-27,Anjali,South,Laptop,49007,35970,2023,6,13037
480,1498,2023-05-08,Aman,East,Tablet,19160,15636,2023,5,3524
481,1500,2023-10-07,Vikas,North,Printer,34567,22426,2023,10,12141

In [47]:
#Engine = create_engine('postgresql+pypostgresql://1234/Salesdb')

!pip install psycopg2-binary

engine = create_engine(
    "postgresql+psycopg2://postgres:1234@localhost:5432/mydatabase"
)

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2_binary-2.9.12-cp314-cp314-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 259.9 kB/s eta 0:00:09
   ------- -------------------------------- 0.5/2.8 MB 259.9 kB/s eta 0:00:09
   ------- -------------------------------- 0.5/2.8 MB 259.9 kB/s eta 0:00:09
   ------- -------------------------------- 0.5/2.8 MB 259.9 kB/s eta 0:00:09
   ------- -------------------------------- 0.5/2.8 MB 259.9 kB/s eta 0:00:09
   ------- -------------------------------- 0.5/2.8 MB 259.9 kB/s eta 0:00:09
   ----------- ---------------------------- 0.8/2.8 MB 247.8 kB/s eta 0:00:09
   ----------- ---------------------------- 0.8/2.8 MB 247.8 kB/s eta 0:00:09
   ----------- ---------------------------- 0.8/2.8 MB 247.8 kB/s eta 0:00:09
   ----------- ---------------------------- 0.8/2.8 MB 247.8 kB/s eta 0:00:09
   ----------- ---------------------------- 0.8/2.8 MB 247.8 kB/s eta 0:00:09
   ----------- ---------------------------- 0.8/2.8 MB 247.8 kB/s eta 0:00:09
   ----------- ---------------------------- 0.8/2.8 MB 247.8 kB/s eta 0:00:09
   ----------- ---------------------------- 0.8/2.8 MB 247.8 kB/s eta 0:00:09
   ----------- ---------------------------- 0.8/2.8 MB 247.8 kB/s eta 0:00:09
   ----------- ---------------------------- 0.8/2.8 MB 247.8 kB/s eta 0:00:09
   -------------- ------------------------- 1.0/2.8 MB 178.7 kB/s eta 0:00:11
   -------------- ------------------------- 1.0/2.8 MB 178.7 kB/s eta 0:00:11
   -------------- ------------------------- 1.0/2.8 MB 178.7 kB/s eta 0:00:11
   -------------- ------------------------- 1.0/2.8 MB 178.7 kB/s eta 0:00:11
   -------------- ------------------------- 1.0/2.8 MB 178.7 kB/s eta 0:00:11
   ------------------ --------------------- 1.3/2.8 MB 194.8 kB/s eta 0:00:08
   ------------------ --------------------- 1.3/2.8 MB 194.8 kB/s eta 0:00:08
   ------------------ --------------------- 1.3/2.8 MB 194.8 kB/s eta 0:00:08
   ------------------ --------------------- 1.3/2.8 MB 194.8 kB/s eta 0:00:08
   ------------------ --------------------- 1.3/2.8 MB 194.8 kB/s eta 0:00:08
   ---------------------- ----------------- 1.6/2.8 MB 205.3 kB/s eta 0:00:07
   ---------------------- ----------------- 1.6/2.8 MB 205.3 kB/s eta 0:00:07
   ---------------------- ----------------- 1.6/2.8 MB 205.3 kB/s eta 0:00:07
   ---------------------- ----------------- 1.6/2.8 MB 205.3 kB/s eta 0:00:07
   ------------------------- -------------- 1.8/2.8 MB 215.9 kB/s eta 0:00:05
   ------------------------- -------------- 1.8/2.8 MB 215.9 kB/s eta 0:00:05
   ------------------------- -------------- 1.8/2.8 MB 215.9 kB/s eta 0:00:05
   ------------------------- -------------- 1.8/2.8 MB 215.9 kB/s eta 0:00:05
   ----------------------------- ---------- 2.1/2.8 MB 226.3 kB/s eta 0:00:04
   ----------------------------- ---------- 2.1/2.8 MB 226.3 kB/s eta 0:00:04
   ----------------------------- ---------- 2.1/2.8 MB 226.3 kB/s eta 0:00:04
   ----------------------------- ---------- 2.1/2.8 MB 226.3 kB/s eta 0:00:04
   --------------------------------- ------ 2.4/2.8 MB 235.8 kB/s eta 0:00:03
   --------------------------------- ------ 2.4/2.8 MB 235.8 kB/s eta 0:00:03
   --------------------------------- ------ 2.4/2.8 MB 235.8 kB/s eta 0:00:03
   ------------------------------------ --- 2.6/2.8 MB 247.2 kB/s eta 0:00:01
   ------------------------------------ --- 2.6/2.8 MB 247.2 kB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 256.4 kB/s  0:00:10
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [48]:
engine = create_engine(
    "postgresql+psycopg2://postgres:1234@localhost:5432/Salesdb"
)

In [54]:
df.to_sql(name='Sales_cleaned_dataset',con=engine,index=False , if_exists='replace')

482